List listContinentsCache = [
  {
    "RegionalID": 20000,
    "ParentID": 0,
    "Name": "Africa",
    "IsActive": "Y",
    "Level": 0,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Africa"
  },
  {
    "RegionalID": 20001,
    "ParentID": 0,
    "Name": "Asia",
    "IsActive": "Y",
    "Level": 0,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Asia"
  },
  {
    "RegionalID": 20002,
    "ParentID": 0,
    "Name": "Europe",
    "IsActive": "Y",
    "Level": 0,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Europe"
  },
  {
    "RegionalID": 20003,
    "ParentID": 0,
    "Name": "North America",
    "IsActive": "Y",
    "Level": 0,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "North America"
  },
  {
    "RegionalID": 20004,
    "ParentID": 0,
    "Name": "Oceania",
    "IsActive": "Y",
    "Level": 0,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Oceania"
  },
  {
    "RegionalID": 20005,
    "ParentID": 0,
    "Name": "South America",
    "IsActive": "Y",
    "Level": 0,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "South America"
  },
  {
    "RegionalID": 20006,
    "ParentID": 0,
    "Name": "Antarctica",
    "IsActive": "Y",
    "Level": 0,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Antarctica"
  }
];

List listCountriesCache = [
  {
    "RegionalID": 2,
    "ParentID": 20001,
    "Name": "Việt Nam",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": "N",
    "Description": "Không xóa bản ghi này nhé",
    "Prefix": null,
    "FullAddress": null
  },
  {
    "RegionalID": 20007,
    "ParentID": 20000,
    "Name": "Algeria",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Algeria, Africa"
  },
  {
    "RegionalID": 20008,
    "ParentID": 20000,
    "Name": "Angola",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Angola, Africa"
  },
  {
    "RegionalID": 20009,
    "ParentID": 20000,
    "Name": "Benin",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Benin, Africa"
  },
  {
    "RegionalID": 20010,
    "ParentID": 20000,
    "Name": "Botswana",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Botswana, Africa"
  },
  {
    "RegionalID": 20011,
    "ParentID": 20000,
    "Name": "Burkina",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Burkina, Africa"
  },
  {
    "RegionalID": 20012,
    "ParentID": 20000,
    "Name": "Burundi",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Burundi, Africa"
  },
  {
    "RegionalID": 20013,
    "ParentID": 20000,
    "Name": "Cameroon",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Cameroon, Africa"
  },
  {
    "RegionalID": 20014,
    "ParentID": 20000,
    "Name": "Cape Verde",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Cape Verde, Africa"
  },
  {
    "RegionalID": 20015,
    "ParentID": 20000,
    "Name": "Central African Republic",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Central African Republic, Africa"
  },
  {
    "RegionalID": 20016,
    "ParentID": 20000,
    "Name": "Chad",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Chad, Africa"
  },
  {
    "RegionalID": 20017,
    "ParentID": 20000,
    "Name": "Comoros",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Comoros, Africa"
  },
  {
    "RegionalID": 20018,
    "ParentID": 20000,
    "Name": "Congo",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Congo, Africa"
  },
  {
    "RegionalID": 20019,
    "ParentID": 20000,
    "Name": "Congo, Democratic Republic of",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Congo, Democratic Republic of, Africa"
  },
  {
    "RegionalID": 20020,
    "ParentID": 20000,
    "Name": "Djibouti",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Djibouti, Africa"
  },
  {
    "RegionalID": 20021,
    "ParentID": 20000,
    "Name": "Egypt",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Egypt, Africa"
  },
  {
    "RegionalID": 20022,
    "ParentID": 20000,
    "Name": "Equatorial Guinea",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Equatorial Guinea, Africa"
  },
  {
    "RegionalID": 20023,
    "ParentID": 20000,
    "Name": "Eritrea",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Eritrea, Africa"
  },
  {
    "RegionalID": 20024,
    "ParentID": 20000,
    "Name": "Ethiopia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Ethiopia, Africa"
  },
  {
    "RegionalID": 20025,
    "ParentID": 20000,
    "Name": "Gabon",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Gabon, Africa"
  },
  {
    "RegionalID": 20026,
    "ParentID": 20000,
    "Name": "Gambia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Gambia, Africa"
  },
  {
    "RegionalID": 20027,
    "ParentID": 20000,
    "Name": "Ghana",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Ghana, Africa"
  },
  {
    "RegionalID": 20028,
    "ParentID": 20000,
    "Name": "Guinea",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Guinea, Africa"
  },
  {
    "RegionalID": 20029,
    "ParentID": 20000,
    "Name": "Guinea-Bissau",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Guinea-Bissau, Africa"
  },
  {
    "RegionalID": 20030,
    "ParentID": 20000,
    "Name": "Ivory Coast",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Ivory Coast, Africa"
  },
  {
    "RegionalID": 20031,
    "ParentID": 20000,
    "Name": "Kenya",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Kenya, Africa"
  },
  {
    "RegionalID": 20032,
    "ParentID": 20000,
    "Name": "Lesotho",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Lesotho, Africa"
  },
  {
    "RegionalID": 20033,
    "ParentID": 20000,
    "Name": "Liberia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Liberia, Africa"
  },
  {
    "RegionalID": 20034,
    "ParentID": 20000,
    "Name": "Libya",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Libya, Africa"
  },
  {
    "RegionalID": 20035,
    "ParentID": 20000,
    "Name": "Madagascar",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Madagascar, Africa"
  },
  {
    "RegionalID": 20036,
    "ParentID": 20000,
    "Name": "Malawi",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Malawi, Africa"
  },
  {
    "RegionalID": 20037,
    "ParentID": 20000,
    "Name": "Mali",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Mali, Africa"
  },
  {
    "RegionalID": 20038,
    "ParentID": 20000,
    "Name": "Mauritania",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Mauritania, Africa"
  },
  {
    "RegionalID": 20039,
    "ParentID": 20000,
    "Name": "Mauritius",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Mauritius, Africa"
  },
  {
    "RegionalID": 20040,
    "ParentID": 20000,
    "Name": "Morocco",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Morocco, Africa"
  },
  {
    "RegionalID": 20041,
    "ParentID": 20000,
    "Name": "Mozambique",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Mozambique, Africa"
  },
  {
    "RegionalID": 20042,
    "ParentID": 20000,
    "Name": "Namibia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Namibia, Africa"
  },
  {
    "RegionalID": 20043,
    "ParentID": 20000,
    "Name": "Niger",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Niger, Africa"
  },
  {
    "RegionalID": 20044,
    "ParentID": 20000,
    "Name": "Nigeria",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Nigeria, Africa"
  },
  {
    "RegionalID": 20045,
    "ParentID": 20000,
    "Name": "Rwanda",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Rwanda, Africa"
  },
  {
    "RegionalID": 20046,
    "ParentID": 20000,
    "Name": "Sao Tome and Principe",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Sao Tome and Principe, Africa"
  },
  {
    "RegionalID": 20047,
    "ParentID": 20000,
    "Name": "Senegal",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Senegal, Africa"
  },
  {
    "RegionalID": 20048,
    "ParentID": 20000,
    "Name": "Seychelles",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Seychelles, Africa"
  },
  {
    "RegionalID": 20049,
    "ParentID": 20000,
    "Name": "Sierra Leone",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Sierra Leone, Africa"
  },
  {
    "RegionalID": 20050,
    "ParentID": 20000,
    "Name": "Somalia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Somalia, Africa"
  },
  {
    "RegionalID": 20051,
    "ParentID": 20000,
    "Name": "South Africa",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "South Africa, Africa"
  },
  {
    "RegionalID": 20052,
    "ParentID": 20000,
    "Name": "South Sudan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "South Sudan, Africa"
  },
  {
    "RegionalID": 20053,
    "ParentID": 20000,
    "Name": "Sudan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Sudan, Africa"
  },
  {
    "RegionalID": 20054,
    "ParentID": 20000,
    "Name": "Swaziland",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Swaziland, Africa"
  },
  {
    "RegionalID": 20055,
    "ParentID": 20000,
    "Name": "Tanzania",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Tanzania, Africa"
  },
  {
    "RegionalID": 20056,
    "ParentID": 20000,
    "Name": "Togo",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Togo, Africa"
  },
  {
    "RegionalID": 20057,
    "ParentID": 20000,
    "Name": "Tunisia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Tunisia, Africa"
  },
  {
    "RegionalID": 20058,
    "ParentID": 20000,
    "Name": "Uganda",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Uganda, Africa"
  },
  {
    "RegionalID": 20059,
    "ParentID": 20000,
    "Name": "Zambia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Zambia, Africa"
  },
  {
    "RegionalID": 20060,
    "ParentID": 20000,
    "Name": "Zimbabwe",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Zimbabwe, Africa"
  },
  {
    "RegionalID": 20061,
    "ParentID": 20001,
    "Name": "Afghanistan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Afghanistan, Asia"
  },
  {
    "RegionalID": 20062,
    "ParentID": 20001,
    "Name": "Bahrain",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Bahrain, Asia"
  },
  {
    "RegionalID": 20063,
    "ParentID": 20001,
    "Name": "Bangladesh",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Bangladesh, Asia"
  },
  {
    "RegionalID": 20064,
    "ParentID": 20001,
    "Name": "Bhutan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Bhutan, Asia"
  },
  {
    "RegionalID": 20065,
    "ParentID": 20001,
    "Name": "Brunei",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Brunei, Asia"
  },
  {
    "RegionalID": 20066,
    "ParentID": 20001,
    "Name": "Burma (Myanmar)",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Burma (Myanmar), Asia"
  },
  {
    "RegionalID": 20067,
    "ParentID": 20001,
    "Name": "Cambodia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Cambodia, Asia"
  },
  {
    "RegionalID": 20068,
    "ParentID": 20001,
    "Name": "China",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "China, Asia"
  },
  {
    "RegionalID": 20069,
    "ParentID": 20001,
    "Name": "East Timor",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "East Timor, Asia"
  },
  {
    "RegionalID": 20070,
    "ParentID": 20001,
    "Name": "India",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "India, Asia"
  },
  {
    "RegionalID": 20071,
    "ParentID": 20001,
    "Name": "Indonesia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Indonesia, Asia"
  },
  {
    "RegionalID": 20072,
    "ParentID": 20001,
    "Name": "Iran",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Iran, Asia"
  },
  {
    "RegionalID": 20073,
    "ParentID": 20001,
    "Name": "Iraq",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Iraq, Asia"
  },
  {
    "RegionalID": 20074,
    "ParentID": 20001,
    "Name": "Israel",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Israel, Asia"
  },
  {
    "RegionalID": 20075,
    "ParentID": 20001,
    "Name": "Japan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Japan, Asia"
  },
  {
    "RegionalID": 20076,
    "ParentID": 20001,
    "Name": "Jordan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Jordan, Asia"
  },
  {
    "RegionalID": 20077,
    "ParentID": 20001,
    "Name": "Kazakhstan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Kazakhstan, Asia"
  },
  {
    "RegionalID": 20078,
    "ParentID": 20001,
    "Name": "Korea, North",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Korea, North, Asia"
  },
  {
    "RegionalID": 20079,
    "ParentID": 20001,
    "Name": "Korea, South",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Korea, South, Asia"
  },
  {
    "RegionalID": 20080,
    "ParentID": 20001,
    "Name": "Kuwait",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Kuwait, Asia"
  },
  {
    "RegionalID": 20081,
    "ParentID": 20001,
    "Name": "Kyrgyzstan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Kyrgyzstan, Asia"
  },
  {
    "RegionalID": 20082,
    "ParentID": 20001,
    "Name": "Laos",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Laos, Asia"
  },
  {
    "RegionalID": 20083,
    "ParentID": 20001,
    "Name": "Lebanon",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Lebanon, Asia"
  },
  {
    "RegionalID": 20084,
    "ParentID": 20001,
    "Name": "Malaysia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Malaysia, Asia"
  },
  {
    "RegionalID": 20085,
    "ParentID": 20001,
    "Name": "Maldives",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Maldives, Asia"
  },
  {
    "RegionalID": 20086,
    "ParentID": 20001,
    "Name": "Mongolia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Mongolia, Asia"
  },
  {
    "RegionalID": 20087,
    "ParentID": 20001,
    "Name": "Nepal",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Nepal, Asia"
  },
  {
    "RegionalID": 20088,
    "ParentID": 20001,
    "Name": "Oman",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Oman, Asia"
  },
  {
    "RegionalID": 20089,
    "ParentID": 20001,
    "Name": "Pakistan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Pakistan, Asia"
  },
  {
    "RegionalID": 20090,
    "ParentID": 20001,
    "Name": "Philippines",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Philippines, Asia"
  },
  {
    "RegionalID": 20091,
    "ParentID": 20001,
    "Name": "Qatar",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Qatar, Asia"
  },
  {
    "RegionalID": 20092,
    "ParentID": 20001,
    "Name": "Russian Federation",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Russian Federation, Asia"
  },
  {
    "RegionalID": 20093,
    "ParentID": 20001,
    "Name": "Saudi Arabia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Saudi Arabia, Asia"
  },
  {
    "RegionalID": 20094,
    "ParentID": 20001,
    "Name": "Singapore",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Singapore, Asia"
  },
  {
    "RegionalID": 20095,
    "ParentID": 20001,
    "Name": "Sri Lanka",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Sri Lanka, Asia"
  },
  {
    "RegionalID": 20096,
    "ParentID": 20001,
    "Name": "Syria",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Syria, Asia"
  },
  {
    "RegionalID": 20097,
    "ParentID": 20001,
    "Name": "Tajikistan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Tajikistan, Asia"
  },
  {
    "RegionalID": 20098,
    "ParentID": 20001,
    "Name": "Thailand",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Thailand, Asia"
  },
  {
    "RegionalID": 20099,
    "ParentID": 20001,
    "Name": "Turkey",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Turkey, Asia"
  },
  {
    "RegionalID": 20100,
    "ParentID": 20001,
    "Name": "Turkmenistan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Turkmenistan, Asia"
  },
  {
    "RegionalID": 20101,
    "ParentID": 20001,
    "Name": "United Arab Emirates",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "United Arab Emirates, Asia"
  },
  {
    "RegionalID": 20102,
    "ParentID": 20001,
    "Name": "Uzbekistan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Uzbekistan, Asia"
  },
  {
    "RegionalID": 20103,
    "ParentID": 20001,
    "Name": "Yemen",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Yemen, Asia"
  },
  {
    "RegionalID": 20104,
    "ParentID": 20002,
    "Name": "Albania",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Albania, Europe"
  },
  {
    "RegionalID": 20105,
    "ParentID": 20002,
    "Name": "Andorra",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Andorra, Europe"
  },
  {
    "RegionalID": 20106,
    "ParentID": 20002,
    "Name": "Armenia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Armenia, Europe"
  },
  {
    "RegionalID": 20107,
    "ParentID": 20002,
    "Name": "Austria",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Austria, Europe"
  },
  {
    "RegionalID": 20108,
    "ParentID": 20002,
    "Name": "Azerbaijan",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Azerbaijan, Europe"
  },
  {
    "RegionalID": 20109,
    "ParentID": 20002,
    "Name": "Belarus",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Belarus, Europe"
  },
  {
    "RegionalID": 20110,
    "ParentID": 20002,
    "Name": "Belgium",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Belgium, Europe"
  },
  {
    "RegionalID": 20111,
    "ParentID": 20002,
    "Name": "Bosnia and Herzegovina",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Bosnia and Herzegovina, Europe"
  },
  {
    "RegionalID": 20112,
    "ParentID": 20002,
    "Name": "Bulgaria",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Bulgaria, Europe"
  },
  {
    "RegionalID": 20113,
    "ParentID": 20002,
    "Name": "Croatia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Croatia, Europe"
  },
  {
    "RegionalID": 20114,
    "ParentID": 20002,
    "Name": "Cyprus",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Cyprus, Europe"
  },
  {
    "RegionalID": 20115,
    "ParentID": 20002,
    "Name": "CZ",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "CZ, Europe"
  },
  {
    "RegionalID": 20116,
    "ParentID": 20002,
    "Name": "Denmark",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Denmark, Europe"
  },
  {
    "RegionalID": 20117,
    "ParentID": 20002,
    "Name": "Estonia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Estonia, Europe"
  },
  {
    "RegionalID": 20118,
    "ParentID": 20002,
    "Name": "Finland",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Finland, Europe"
  },
  {
    "RegionalID": 20119,
    "ParentID": 20002,
    "Name": "France",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "France, Europe"
  },
  {
    "RegionalID": 20120,
    "ParentID": 20002,
    "Name": "Georgia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Georgia, Europe"
  },
  {
    "RegionalID": 20121,
    "ParentID": 20002,
    "Name": "Germany",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Germany, Europe"
  },
  {
    "RegionalID": 20122,
    "ParentID": 20002,
    "Name": "Greece",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Greece, Europe"
  },
  {
    "RegionalID": 20123,
    "ParentID": 20002,
    "Name": "Hungary",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Hungary, Europe"
  },
  {
    "RegionalID": 20124,
    "ParentID": 20002,
    "Name": "Iceland",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Iceland, Europe"
  },
  {
    "RegionalID": 20125,
    "ParentID": 20002,
    "Name": "Ireland",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Ireland, Europe"
  },
  {
    "RegionalID": 20126,
    "ParentID": 20002,
    "Name": "Italy",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Italy, Europe"
  },
  {
    "RegionalID": 20127,
    "ParentID": 20002,
    "Name": "Latvia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Latvia, Europe"
  },
  {
    "RegionalID": 20128,
    "ParentID": 20002,
    "Name": "Liechtenstein",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Liechtenstein, Europe"
  },
  {
    "RegionalID": 20129,
    "ParentID": 20002,
    "Name": "Lithuania",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Lithuania, Europe"
  },
  {
    "RegionalID": 20130,
    "ParentID": 20002,
    "Name": "Luxembourg",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Luxembourg, Europe"
  },
  {
    "RegionalID": 20131,
    "ParentID": 20002,
    "Name": "Macedonia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Macedonia, Europe"
  },
  {
    "RegionalID": 20132,
    "ParentID": 20002,
    "Name": "Malta",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Malta, Europe"
  },
  {
    "RegionalID": 20133,
    "ParentID": 20002,
    "Name": "Moldova",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Moldova, Europe"
  },
  {
    "RegionalID": 20134,
    "ParentID": 20002,
    "Name": "Monaco",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Monaco, Europe"
  },
  {
    "RegionalID": 20135,
    "ParentID": 20002,
    "Name": "Montenegro",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Montenegro, Europe"
  },
  {
    "RegionalID": 20136,
    "ParentID": 20002,
    "Name": "Netherlands",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Netherlands, Europe"
  },
  {
    "RegionalID": 20137,
    "ParentID": 20002,
    "Name": "Norway",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Norway, Europe"
  },
  {
    "RegionalID": 20138,
    "ParentID": 20002,
    "Name": "Poland",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Poland, Europe"
  },
  {
    "RegionalID": 20139,
    "ParentID": 20002,
    "Name": "Portugal",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Portugal, Europe"
  },
  {
    "RegionalID": 20140,
    "ParentID": 20002,
    "Name": "Romania",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Romania, Europe"
  },
  {
    "RegionalID": 20141,
    "ParentID": 20002,
    "Name": "San Marino",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "San Marino, Europe"
  },
  {
    "RegionalID": 20142,
    "ParentID": 20002,
    "Name": "Serbia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Serbia, Europe"
  },
  {
    "RegionalID": 20143,
    "ParentID": 20002,
    "Name": "Slovakia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Slovakia, Europe"
  },
  {
    "RegionalID": 20144,
    "ParentID": 20002,
    "Name": "Slovenia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Slovenia, Europe"
  },
  {
    "RegionalID": 20145,
    "ParentID": 20002,
    "Name": "Spain",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Spain, Europe"
  },
  {
    "RegionalID": 20146,
    "ParentID": 20002,
    "Name": "Sweden",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Sweden, Europe"
  },
  {
    "RegionalID": 20147,
    "ParentID": 20002,
    "Name": "Switzerland",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Switzerland, Europe"
  },
  {
    "RegionalID": 20148,
    "ParentID": 20002,
    "Name": "Ukraine",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Ukraine, Europe"
  },
  {
    "RegionalID": 20149,
    "ParentID": 20002,
    "Name": "United Kingdom",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "United Kingdom, Europe"
  },
  {
    "RegionalID": 20150,
    "ParentID": 20002,
    "Name": "Vatican City",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Vatican City, Europe"
  },
  {
    "RegionalID": 20151,
    "ParentID": 20003,
    "Name": "Antigua and Barbuda",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Antigua and Barbuda, North America"
  },
  {
    "RegionalID": 20152,
    "ParentID": 20003,
    "Name": "Bahamas",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Bahamas, North America"
  },
  {
    "RegionalID": 20153,
    "ParentID": 20003,
    "Name": "Barbados",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Barbados, North America"
  },
  {
    "RegionalID": 20154,
    "ParentID": 20003,
    "Name": "Belize",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Belize, North America"
  },
  {
    "RegionalID": 20155,
    "ParentID": 20003,
    "Name": "Canada",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Canada, North America"
  },
  {
    "RegionalID": 20156,
    "ParentID": 20003,
    "Name": "Costa Rica",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Costa Rica, North America"
  },
  {
    "RegionalID": 20157,
    "ParentID": 20003,
    "Name": "Cuba",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Cuba, North America"
  },
  {
    "RegionalID": 20158,
    "ParentID": 20003,
    "Name": "Dominica",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Dominica, North America"
  },
  {
    "RegionalID": 20159,
    "ParentID": 20003,
    "Name": "Dominican Republic",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Dominican Republic, North America"
  },
  {
    "RegionalID": 20160,
    "ParentID": 20003,
    "Name": "El Salvador",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "El Salvador, North America"
  },
  {
    "RegionalID": 20161,
    "ParentID": 20003,
    "Name": "Grenada",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Grenada, North America"
  },
  {
    "RegionalID": 20162,
    "ParentID": 20003,
    "Name": "Guatemala",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Guatemala, North America"
  },
  {
    "RegionalID": 20163,
    "ParentID": 20003,
    "Name": "Haiti",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Haiti, North America"
  },
  {
    "RegionalID": 20164,
    "ParentID": 20003,
    "Name": "Honduras",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Honduras, North America"
  },
  {
    "RegionalID": 20165,
    "ParentID": 20003,
    "Name": "Jamaica",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Jamaica, North America"
  },
  {
    "RegionalID": 20166,
    "ParentID": 20003,
    "Name": "Mexico",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Mexico, North America"
  },
  {
    "RegionalID": 20167,
    "ParentID": 20003,
    "Name": "Nicaragua",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Nicaragua, North America"
  },
  {
    "RegionalID": 20168,
    "ParentID": 20003,
    "Name": "Panama",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Panama, North America"
  },
  {
    "RegionalID": 20169,
    "ParentID": 20003,
    "Name": "Saint Kitts and Nevis",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Saint Kitts and Nevis, North America"
  },
  {
    "RegionalID": 20170,
    "ParentID": 20003,
    "Name": "Saint Lucia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Saint Lucia, North America"
  },
  {
    "RegionalID": 20171,
    "ParentID": 20003,
    "Name": "Saint Vincent and the Grenadines",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Saint Vincent and the Grenadines, North America"
  },
  {
    "RegionalID": 20172,
    "ParentID": 20003,
    "Name": "Trinidad and Tobago",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Trinidad and Tobago, North America"
  },
  {
    "RegionalID": 20173,
    "ParentID": 20003,
    "Name": "US",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "US, North America"
  },
  {
    "RegionalID": 20174,
    "ParentID": 20004,
    "Name": "Australia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Australia, Oceania"
  },
  {
    "RegionalID": 20175,
    "ParentID": 20004,
    "Name": "Fiji",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Fiji, Oceania"
  },
  {
    "RegionalID": 20176,
    "ParentID": 20004,
    "Name": "Kiribati",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Kiribati, Oceania"
  },
  {
    "RegionalID": 20177,
    "ParentID": 20004,
    "Name": "Marshall Islands",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Marshall Islands, Oceania"
  },
  {
    "RegionalID": 20178,
    "ParentID": 20004,
    "Name": "Micronesia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Micronesia, Oceania"
  },
  {
    "RegionalID": 20179,
    "ParentID": 20004,
    "Name": "Nauru",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Nauru, Oceania"
  },
  {
    "RegionalID": 20180,
    "ParentID": 20004,
    "Name": "New Zealand",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "New Zealand, Oceania"
  },
  {
    "RegionalID": 20181,
    "ParentID": 20004,
    "Name": "Palau",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Palau, Oceania"
  },
  {
    "RegionalID": 20182,
    "ParentID": 20004,
    "Name": "Papua New Guinea",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Papua New Guinea, Oceania"
  },
  {
    "RegionalID": 20183,
    "ParentID": 20004,
    "Name": "Samoa",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Samoa, Oceania"
  },
  {
    "RegionalID": 20184,
    "ParentID": 20004,
    "Name": "Solomon Islands",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Solomon Islands, Oceania"
  },
  {
    "RegionalID": 20185,
    "ParentID": 20004,
    "Name": "Tonga",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Tonga, Oceania"
  },
  {
    "RegionalID": 20186,
    "ParentID": 20004,
    "Name": "Tuvalu",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Tuvalu, Oceania"
  },
  {
    "RegionalID": 20187,
    "ParentID": 20004,
    "Name": "Vanuatu",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Vanuatu, Oceania"
  },
  {
    "RegionalID": 20188,
    "ParentID": 20005,
    "Name": "Argentina",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Argentina, South America"
  },
  {
    "RegionalID": 20189,
    "ParentID": 20005,
    "Name": "Bolivia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Bolivia, South America"
  },
  {
    "RegionalID": 20190,
    "ParentID": 20005,
    "Name": "Brazil",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Brazil, South America"
  },
  {
    "RegionalID": 20191,
    "ParentID": 20005,
    "Name": "Chile",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Chile, South America"
  },
  {
    "RegionalID": 20192,
    "ParentID": 20005,
    "Name": "Colombia",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Colombia, South America"
  },
  {
    "RegionalID": 20193,
    "ParentID": 20005,
    "Name": "Ecuador",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Ecuador, South America"
  },
  {
    "RegionalID": 20194,
    "ParentID": 20005,
    "Name": "Guyana",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Guyana, South America"
  },
  {
    "RegionalID": 20195,
    "ParentID": 20005,
    "Name": "Paraguay",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Paraguay, South America"
  },
  {
    "RegionalID": 20196,
    "ParentID": 20005,
    "Name": "Peru",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Peru, South America"
  },
  {
    "RegionalID": 20197,
    "ParentID": 20005,
    "Name": "Suriname",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Suriname, South America"
  },
  {
    "RegionalID": 20198,
    "ParentID": 20005,
    "Name": "Uruguay",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Uruguay, South America"
  },
  {
    "RegionalID": 20199,
    "ParentID": 20005,
    "Name": "Venezuela",
    "IsActive": "Y",
    "Level": 1,
    "CityFlag": null,
    "Description": null,
    "Prefix": null,
    "FullAddress": "Venezuela, South America"
  }
];
